# Generated by Django 3.0.6 on 2022-09-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_feature_selection_erro_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others_1dreconstruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(default=0, null=True)),
                ('task_name', models.CharField(max_length=89)),
                ('inputFile', models.FileField(blank=True, default=0, null=True, upload_to='others/1dreconstruct/inputFile')),
                ('outputFile', models.FileField(blank=True, default=0, null=True, upload_to='others/1dreconstruct/outputFile')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feature_selection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
